import { AuditLogEntry } from "./types";

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "aud_1",
    title: "Organization Approved",
    type: "Approval",
    desc: "Approved Acme Corp application for Platform access.",
    timestamp: "2024-04-06 15:45",
    updatedBy: { name: "Yon Yusuf", email: "yon@welluber.com" },
    entity: { id: "org_1", name: "Acme Corp", type: "Organization" },
  },
  {
    id: "aud_2",
    title: "Benefit Policy Created",
    type: "Create",
    desc: "New 'Premium Health v2' policy created by Host Admin.",
    timestamp: "2024-04-06 14:20",
    updatedBy: { name: "Yon Yusuf", email: "yon@welluber.com" },
    entity: { id: "pol_1", name: "Premium Health v2", type: "Policy" },
  },
  {
    id: "aud_3",
    title: "Service Provider Payout",
    type: "Payout",
    desc: "Triggered monthly payout for 'MediCare Clinic Group'.",
    timestamp: "2024-04-06 11:30",
    updatedBy: { name: "Sarah Chen", email: "sarah@welluber.com" },
    entity: { id: "sp_1", name: "MediCare Clinic Group", type: "ServiceProvider" },
  },
  {
    id: "aud_4",
    title: "System Settings Updated",
    type: "SettingChange",
    desc: "Voucher validity period increased from 15 to 30 days.",
    timestamp: "2024-04-05 16:50",
    updatedBy: { name: "Yon Yusuf", email: "yon@welluber.com" },
    entity: { id: "sys_1", name: "System Settings", type: "System" },
  },
  {
    id: "aud_5",
    title: "New Brand Added",
    type: "Create",
    desc: "Onboarded 'Fitness Pro' brand into the ecosystem.",
    timestamp: "2024-04-05 10:15",
    updatedBy: { name: "Danish Azhar", email: "danish@welluber.com" },
    entity: { id: "br_1", name: "Fitness Pro", type: "Brand" },
  },
  {
    id: "aud_6",
    title: "Administrator Invited",
    type: "Create",
    desc: "Invited 'John Doe' as a Viewer to the Host Portal.",
    timestamp: "2024-04-05 09:00",
    updatedBy: { name: "Yon Yusuf", email: "yon@welluber.com" },
  },
  {
    id: "aud_7",
    title: "Payout API Failure",
    type: "SettingChange",
    desc: "Maybank API returned 503 Service Unavailable during batch payout.",
    timestamp: "2024-04-04 22:15",
    updatedBy: { name: "System", email: "system@welluber.com" },
    entity: { id: "sys_1", name: "Payout API", type: "System" },
  },
];
