import { Organization } from "./types";

export const MOCK_ORGS: Organization[] = [
  {
    id: "ORG-20260115-0001",
    name: "Acme Corporation Sdn Bhd",
    registrationNumber: "1234567-T",
    industry: "Technology",
    subIndustry: "SaaS / Enterprise Software",
    type: "enterprise",
    financialYearStart: "2026-01-01T00:00:00Z",
    subscription: {
      plan: "enterprise",
      billingInformation: "Acme Finance Dept",
      paymentMethod: "bank_transfer",
      startDate: "2026-01-15T10:00:00Z",
      status: "active",
    },
    status: "active",
    tinNumber: "TR-882910-01",
    bankAccountDetails: {
      bankName: "Maybank Berhad",
      accountNumber: "5140 1234 5678",
      accountName: "Acme Corporation Sdn Bhd",
    },
    employeeCount: 450,
    picId: "USER-ADMIN-001",
    utilizationRate: 68,
    claimsCount: 24,
    totalWalletBalance: 45200,
    walletLimit: 60000,
    creditLimit: 10000,
    needsAction: [],
    services: ["Health Screenings", "Clinical Therapy"],
    policies: ["Comprehensive Health", "Mental Health Support"],
    branches: ["Kuala Lumpur HQ", "Subang Jaya", "Penang Office"],
    documents: [],
    employeesWithoutPolicy: 0,
    tierConfigs: [
      { id: "tc1", name: "Executive", code: "EXE" },
      { id: "tc2", name: "Senior Manager", code: "SM" },
      { id: "tc3", name: "Manager", code: "MGR" },
      { id: "tc4", name: "Executive Associate", code: "EA" },
    ],
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "ORG-20260301-0002",
    name: "Global Tech Solutions",
    registrationNumber: "9876543-K",
    industry: "Logistics",
    subIndustry: "Supply Chain",
    type: "sme",
    financialYearStart: "2026-04-01T00:00:00Z",
    subscription: {
      plan: "standard",
      billingInformation: "GT Logistics Finance",
      paymentMethod: "credit_card",
      startDate: "2026-03-01T10:00:00Z",
      status: "active",
    },
    status: "pending",
    tinNumber: "TR-993021-02",
    bankAccountDetails: {
      bankName: "CIMB Bank",
      accountNumber: "8001 2233 4455",
      accountName: "Global Tech Solutions",
    },
    employeeCount: 120,
    picId: null,
    utilizationRate: 15,
    claimsCount: 8,
    totalWalletBalance: 12500,
    walletLimit: 85000,
    creditLimit: 15000,
    needsAction: ["Missing PIC"],
    services: ["General Practice", "Health Screenings"],
    policies: ["Basic GP", "Group Term Life"],
    branches: ["Petaling Jaya Branch"],
    documents: [],
    employeesWithoutPolicy: 12,
    tierConfigs: [
      { id: "tc5", name: "Director", code: "DIR" },
      { id: "tc6", name: "Associate", code: "ASC" },
    ],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "ORG-20260310-0003",
    name: "Nexus Innovations",
    registrationNumber: "5544332-M",
    industry: "Finance",
    subIndustry: "FinTech",
    type: "enterprise",
    financialYearStart: "2026-01-01T00:00:00Z",
    subscription: {
      plan: "premium",
      billingInformation: "Nexus Accounts",
      paymentMethod: "bank_transfer",
      startDate: "2026-02-10T10:00:00Z",
      status: "suspended",
    },
    status: "suspended",
    tinNumber: "TR-554433-03",
    bankAccountDetails: {
      bankName: "Public Bank",
      accountNumber: "3112 5544 3322",
      accountName: "Nexus Innovations",
    },
    employeeCount: 850,
    picId: "USER-ADMIN-002",
    utilizationRate: 92,
    claimsCount: 156,
    totalWalletBalance: 4800,
    walletLimit: 5000,
    creditLimit: 2000,
    needsAction: ["Account low", "No policies"],
    services: ["Clinical Therapy", "Specialist Care"],
    policies: [],
    branches: ["Singapore HQ", "KL Office"],
    documents: [],
    employeesWithoutPolicy: 850,
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
  },
  ...Array.from({ length: 7 }, (_, i) => ({
    id: `ORG-20260401-001${i + 4}`,
    name: `Enterprise Partner ${i + 1} Sdn Bhd`,
    registrationNumber: `${1000000 + i}-X`,
    industry: "Manufacturing",
    subIndustry: "Industrial Goods",
    type: "enterprise" as const,
    financialYearStart: "2026-01-01T00:00:00Z",
    subscription: {
      plan: "standard" as const,
      billingInformation: "Finance Dept",
      paymentMethod: "bank_transfer",
      startDate: "2026-04-01T10:00:00Z",
      status: "active" as const,
    },
    status: "active" as const,
    tinNumber: `TR-000${i}-04`,
    bankAccountDetails: {
      bankName: "Maybank Berhad",
      accountNumber: `5140 ${1000 + i} 5678`,
      accountName: `Enterprise Partner ${i + 1} Sdn Bhd`,
    },
    employeeCount: 200 + i * 50,
    picId: "USER-ADMIN-001",
    utilizationRate: 45 + i * 2,
    claimsCount: 12 + i,
    totalWalletBalance: 35000 + i * 1000,
    walletLimit: 80000,
    creditLimit: 20000 + i * 5000,
    needsAction: i % 4 === 0 ? ["No branches"] : [],
    services: ["Occupational Health", "Gymnasium Facilities"],
    policies: ["Standard Medical"],
    branches: ["Main Plant"],
    documents: [],
    employeesWithoutPolicy: i % 3 === 0 ? 10 : 0,
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z",
  } as Organization)),
];
