import type { ServiceProvider } from "@/types/provider";
import { DEFAULT_OPERATING_HOURS } from "./constants";

export const MOCK_SPS: ServiceProvider[] = [
  {
    id: "SP-20260101-0001",
    brandId: "BRD-001",
    name: "Zenith Yoga Studio",
    registrationNo: "1122334-A",
    serviceCategories: ["Yoga & Pilates", "Mental Health & Mindfulness"],
    mainServices: ["Yoga", "Meditation", "Therapy & Counselling", "Life & Executive Coaching", "Sound & Sensory Therapy", "Art & Expressive Therapy"],
    description: "Premium yoga and mindfulness centre with certified instructors.",
    website: "https://zenithyoga.my",
    isActive: true,
    status: "active",
    taxProfile: {
      isTaxRegistered: true,
      taxRegNo: "SST-2024-001234",
      taxRate: 0.08,
    },
    commissionSchema: [
      { mainService: "Yoga", tiers: [{ limit: 0, rate: 0.12 }], lastUpdated: "2026-01-10T00:00:00Z" },
      { mainService: "Meditation", tiers: [{ limit: 0, rate: 0.20 }], lastUpdated: "2026-01-10T00:00:00Z" },
      { mainService: "Therapy & Counselling", tiers: [{ limit: 0, rate: 0.25 }], lastUpdated: "2026-01-10T00:00:00Z" },
    ],
    admins: [
      { id: "SPA-001", spId: "SP-20260101-0001", name: "Sara Lim", email: "sara@zenithyoga.my", status: "active", invitedAt: "2026-01-05T00:00:00Z", branchIds: [] },
    ],
    branches: [
      {
        id: "SPB-001",
        spId: "SP-20260101-0001",
        name: "Zenith KLCC",
        services: [
          { service: "Yoga", subServices: ["Vinyasa Flow", "Hatha Yoga"] },
          { service: "Therapy & Counselling", subServices: ["Individual Therapy"] },
        ],
        address: { line: "Lot 5, Suria KLCC", city: "Kuala Lumpur", state: "Wilayah Persekutuan", country: "Malaysia", postalCode: "50088", lat: 3.1579, lon: 101.7123 },
        contacts: [{ name: "Ahmad Razif", email: "razif@zenithyoga.my", type: "branch_manager", phone: "+60112345678", isPublic: true }],
        administrators: [],
        isActive: true,
        operatingHours: DEFAULT_OPERATING_HOURS,
        benefits: ["Changing Room", "Shower", "Locker", "Free WiFi", "Towel Service"],
      },
      {
        id: "SPB-002",
        spId: "SP-20260101-0001",
        name: "Zenith Mont Kiara",
        services: [{ service: "Yoga", subServices: ["Vinyasa Flow"] }],
        address: { line: "G-07, Solaris Dutamas", city: "Kuala Lumpur", state: "Wilayah Persekutuan", country: "Malaysia", postalCode: "50480" },
        contacts: [{ name: "Priya Nair", email: "priya@zenithyoga.my", type: "branch_manager", phone: "+60123456789", isPublic: true }],
        administrators: [],
        isActive: true,
        operatingHours: DEFAULT_OPERATING_HOURS,
        benefits: ["Changing Room", "Free WiFi"],
      },
    ],
    vouchers: [
      {
        id: "VCH-001",
        spId: "SP-20260101-0001",
        code: "PACSP000010001",
        name: "Monthly Yoga Pass",
        description: "Unlimited yoga classes for one month at any Zenith branch.",
        photo: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800",
        bookingRequired: true,
        displayLocation: { line: "" },
        serviceLines: [{ service: "Yoga", subServices: ["Vinyasa Yoga"], description: "Unlimited drop-in sessions", descriptionList: "• Unlimited access\n• Free mat provided" }],
        status: "activated",
        isActive: true,
        activationPeriod: { startDate: "2026-02-01T00:00:00Z", endDate: "2026-12-31T00:00:00Z" },
        currency: "MYR",
        initialPrice: 280,
        finalPrice: 250,
        validationDuration: { unit: "months", value: 1 },
        redemptionPeriod: { mode: "after_purchase", unit: "day", value: 7 },
        membershipStartDay: "1st",
        branchScope: "all",
        branchIds: [],
        createdAt: "2026-02-01T00:00:00Z",
        updatedAt: "2026-02-01T00:00:00Z",
      },
    ],
    activeVoucherCount: 1,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "SP-20260115-0002",
    brandId: "BRD-002",
    name: "AgileMind Therapy Centre",
    registrationNo: "5566778-B",
    serviceCategories: ["Mental Health & Mindfulness"],
    mainServices: ["Therapy & Counselling", "Life & Executive Coaching"],
    description: "Licensed clinical therapists and certified life coaches.",
    website: "https://agilemind.my",
    isActive: true,
    status: "active",
    taxProfile: { isTaxRegistered: false, taxRate: 0.08 },
    commissionSchema: [
      { mainService: "Therapy & Counselling", tiers: [{ limit: 0, rate: 0.20 }], lastUpdated: "2026-01-20T00:00:00Z" },
      { mainService: "Life & Executive Coaching", tiers: [{ limit: 0, rate: 0.15 }], lastUpdated: "2026-01-20T00:00:00Z" },
    ],
    admins: [
      { id: "SPA-002", spId: "SP-20260115-0002", name: "Dr. James Wong", email: "james@agilemind.my", status: "active", invitedAt: "2026-01-12T00:00:00Z", branchIds: [] },
    ],
    branches: [
      {
        id: "SPB-003",
        spId: "SP-20260115-0002",
        name: "AgileMind PJ",
        services: [{ service: "Therapy & Counselling", subServices: ["Individual Therapy", "Group Counselling"] }],
        address: { line: "Level 10, PJ Trade Centre", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", postalCode: "46200" },
        contacts: [{ name: "Nurul Ain", email: "ain@agilemind.my", type: "reception", phone: "+60198765432", isPublic: true }],
        administrators: [],
        isActive: true,
        operatingHours: { ...DEFAULT_OPERATING_HOURS, sat: { open: "09:00", close: "13:00", isClosed: false }, sun: { open: "09:00", close: "13:00", isClosed: true } },
        benefits: ["Private Consultation Room", "Waiting Area", "Free WiFi"],
      },
    ],
    vouchers: [
      {
        id: "VCH-002",
        spId: "SP-20260115-0002",
        code: "PACSP000020001",
        name: "Individual Therapy Session",
        description: "One 60-minute individual therapy session with a licensed therapist.",
        photo: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=800",
        bookingRequired: true,
        displayLocation: { line: "" },
        serviceLines: [{ service: "Therapy & Counselling", subServices: ["Individual Therapy"], description: "60-min licensed therapist session", descriptionList: "• 1-on-1 session\n• Licensed practitioners" }],
        status: "activated",
        isActive: true,
        activationPeriod: { startDate: "2026-02-01T00:00:00Z" },
        currency: "MYR",
        initialPrice: 220,
        finalPrice: 200,
        validationDuration: { unit: "months", value: 3 },
        redemptionPeriod: { mode: "after_purchase", unit: "day", value: 30 },
        membershipStartDay: "none",
        branchScope: "all",
        branchIds: [],
        createdAt: "2026-02-01T00:00:00Z",
        updatedAt: "2026-02-01T00:00:00Z",
      },
    ],
    activeVoucherCount: 1,
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "SP-20260201-0003",
    brandId: "BRD-003",
    name: "CoreFit Rehabilitation",
    registrationNo: "9988776-C",
    serviceCategories: ["Medical & Allied Health", "Recovery & Rehabilitation"],
    mainServices: ["Physiotherapy", "Sports Recovery"],
    description: "Sports rehabilitation and physiotherapy specialists.",
    website: "https://corefit.my",
    isActive: true,
    status: "pending",
    taxProfile: { isTaxRegistered: true, taxRegNo: "SST-2024-005678", taxRate: 0.08 },
    commissionSchema: [],
    admins: [
      { id: "SPA-003", spId: "SP-20260201-0003", name: "Chong Wei Lin", email: "wei@corefit.my", status: "pending_activation", invitedAt: "2026-02-03T00:00:00Z", branchIds: [] },
    ],
    branches: [],
    vouchers: [],
    activeVoucherCount: 0,
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "SP-20260210-0004",
    brandId: "BRD-004",
    name: "Serenity Spa & Aesthetics",
    registrationNo: "3344556-D",
    serviceCategories: ["Spa & Aesthetics", "Massage & Bodywork"],
    mainServices: ["Traditional / Relaxation Massage", "Face & Skin Care"],
    description: "Premium spa treatments and aesthetic services.",
    website: "https://serenityspa.my",
    isActive: false,
    status: "suspended",
    taxProfile: { isTaxRegistered: true, taxRegNo: "SST-2023-009012", taxRate: 0.08 },
    commissionSchema: [
      { mainService: "Traditional / Relaxation Massage", tiers: [{ limit: 0, rate: 0.15 }], lastUpdated: "2026-02-15T00:00:00Z" },
      { mainService: "Face & Skin Care", tiers: [{ limit: 0, rate: 0.15 }], lastUpdated: "2026-02-15T00:00:00Z" },
    ],
    admins: [
      { id: "SPA-004", spId: "SP-20260210-0004", name: "Mei Ling Tan", email: "mei@serenityspa.my", status: "active", invitedAt: "2026-02-12T00:00:00Z", branchIds: [] },
    ],
    branches: [
      {
        id: "SPB-004",
        spId: "SP-20260210-0004",
        name: "Serenity Pavilion KL",
        services: [
          { service: "Traditional / Relaxation Massage", subServices: ["Swedish Massage"] },
          { service: "Face & Skin Care", subServices: ["Classic Facial"] },
        ],
        address: { line: "Level 5, Pavilion Kuala Lumpur", city: "Kuala Lumpur", state: "Wilayah Persekutuan", country: "Malaysia", postalCode: "55100", lat: 3.1488, lon: 101.7131 },
        contacts: [{ name: "Lena Yap", email: "lena@serenityspa.my", type: "branch_manager", phone: "+60161234567", isPublic: true }],
        administrators: [],
        isActive: false,
        operatingHours: DEFAULT_OPERATING_HOURS,
        benefits: ["Private Rooms", "Steam Room", "Relaxation Lounge", "Free WiFi", "Parking"],
      },
    ],
    vouchers: [],
    activeVoucherCount: 0,
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `SP-20260301-000${i + 5}`,
    brandId: "BRD-001",
    name: `Wellness Partner ${i + 1} Sdn Bhd`,
    registrationNo: `${7000000 + i}-X`,
    serviceCategories: i % 2 === 0 ? ["Fitness & Exercise"] : ["Nutrition & Dietetics", "Medical & Allied Health"],
    mainServices: i % 2 === 0 ? ["Gym Access"] : ["Nutritional Counselling", "Physiotherapy"],
    description: `Certified wellness centre offering quality health services.`,
    website: "https://partner.my",
    isActive: true,
    status: "active" as const,
    taxProfile: { isTaxRegistered: false, taxRate: 0.08 },
    commissionSchema: [
      { mainService: i % 2 === 0 ? "Gym Access" : "Nutritional Counselling", tiers: [{ limit: 0, rate: 0.12 }], lastUpdated: "2026-03-01T00:00:00Z" },
    ],
    admins: [],
    branches: [],
    vouchers: [],
    activeVoucherCount: i + 1,
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  } satisfies ServiceProvider)),
];
