import type { ServiceProvider } from "@/types/provider";
import { DEFAULT_OPERATING_HOURS } from "./constants";

export const MOCK_SPS: ServiceProvider[] = [
  {
    id: "SP-20260101-0001",
    name: "Zenith Yoga Studio",
    registrationNo: "1122334-A",
    serviceCategories: ["Physical Wellbeing", "Mindfulness & Mental"],
    description: "Premium yoga and mindfulness centre with certified instructors.",
    website: "https://zenithyoga.my",
    isActive: true,
    status: "active",
    taxProfile: {
      isTaxRegistered: true,
      taxRegNo: "SST-2024-001234",
      taxRate: 0.08,
    },
    commissionSchema: [
      { serviceCategory: "Physical Wellbeing", commissionRate: 0.12, expiredCommissionRate: 0.12, lastUpdated: "2026-01-10T00:00:00Z" },
      { serviceCategory: "Mindfulness & Mental", commissionRate: 0.20, expiredCommissionRate: 0.18, lastUpdated: "2026-01-10T00:00:00Z" },
    ],
    admins: [
      { id: "SPA-001", spId: "SP-20260101-0001", name: "Sara Lim", email: "sara@zenithyoga.my", status: "active", invitedAt: "2026-01-05T00:00:00Z" },
    ],
    branches: [
      {
        id: "SPB-001",
        spId: "SP-20260101-0001",
        name: "Zenith KLCC",
        services: ["Physical Wellbeing", "Mindfulness & Mental"],
        address: { line: "Lot 5, Suria KLCC", city: "Kuala Lumpur", state: "Wilayah Persekutuan", country: "Malaysia", postalCode: "50088", lat: 3.1579, lon: 101.7123 },
        contacts: [{ name: "Ahmad Razif", type: "branch_manager", phone: "+60112345678", isPublic: true }],
        isActive: true,
        operatingHours: DEFAULT_OPERATING_HOURS,
        facilities: ["Changing Room", "Shower", "Locker", "Free WiFi", "Towel Service"],
      },
      {
        id: "SPB-002",
        spId: "SP-20260101-0001",
        name: "Zenith Mont Kiara",
        services: ["Physical Wellbeing"],
        address: { line: "G-07, Solaris Dutamas", city: "Kuala Lumpur", state: "Wilayah Persekutuan", country: "Malaysia", postalCode: "50480" },
        contacts: [{ name: "Priya Nair", type: "branch_manager", phone: "+60123456789", isPublic: true }],
        isActive: true,
        operatingHours: DEFAULT_OPERATING_HOURS,
        facilities: ["Changing Room", "Free WiFi"],
      },
    ],
    vouchers: [
      {
        id: "VCH-001",
        spId: "SP-20260101-0001",
        code: "PACSP000010001",
        name: "Monthly Yoga Pass",
        description: "Unlimited yoga classes for one month at any Zenith branch.",
        serviceLines: [{ serviceCategory: "Physical Wellbeing", subServiceLabel: "Group Yoga Class", description: "Unlimited drop-in sessions", duration: { unit: "month", value: 1 }, weight: 1.0 }],
        status: "activated",
        isActive: true,
        activationPeriod: { startDate: "2026-02-01T00:00:00Z", endDate: "2026-12-31T00:00:00Z" },
        currency: "MYR",
        initialPrice: 280,
        finalPrice: 250,
        validationDuration: { unit: "months", value: 1 },
        redemptionPeriod: { mode: "after_purchase", unit: "day", value: 7 },
        membershipStartDay: "1st",
        branchScope: "all",
        branchIds: [],
        createdAt: "2026-02-01T00:00:00Z",
        updatedAt: "2026-02-01T00:00:00Z",
      },
    ],
    activeVoucherCount: 1,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "SP-20260115-0002",
    name: "AgileMind Therapy Centre",
    registrationNo: "5566778-B",
    serviceCategories: ["Psychological Wellbeing"],
    description: "Licensed clinical therapists and certified life coaches.",
    website: "https://agilemind.my",
    isActive: true,
    status: "active",
    taxProfile: { isTaxRegistered: false, taxRate: 0.08 },
    commissionSchema: [
      { serviceCategory: "Psychological Wellbeing", commissionRate: 0.20, expiredCommissionRate: 0.18, lastUpdated: "2026-01-20T00:00:00Z" },
    ],
    admins: [
      { id: "SPA-002", spId: "SP-20260115-0002", name: "Dr. James Wong", email: "james@agilemind.my", status: "active", invitedAt: "2026-01-12T00:00:00Z" },
    ],
    branches: [
      {
        id: "SPB-003",
        spId: "SP-20260115-0002",
        name: "AgileMind PJ",
        services: ["Psychological Wellbeing"],
        address: { line: "Level 10, PJ Trade Centre", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", postalCode: "46200" },
        contacts: [{ name: "Nurul Ain", type: "reception", phone: "+60198765432", isPublic: true }],
        isActive: true,
        operatingHours: { ...DEFAULT_OPERATING_HOURS, sat: { open: "09:00", close: "13:00", isClosed: false }, sun: { open: "09:00", close: "13:00", isClosed: true } },
        facilities: ["Private Consultation Room", "Waiting Area", "Free WiFi"],
      },
    ],
    vouchers: [
      {
        id: "VCH-002",
        spId: "SP-20260115-0002",
        code: "PACSP000020001",
        name: "Individual Therapy Session",
        description: "One 60-minute individual therapy session with a licensed therapist.",
        serviceLines: [{ serviceCategory: "Psychological Wellbeing", subServiceLabel: "Individual Therapy", description: "60-min licensed therapist session", duration: { unit: "hr", value: 1 }, weight: 1.0 }],
        status: "activated",
        isActive: true,
        activationPeriod: { startDate: "2026-02-01T00:00:00Z" },
        currency: "MYR",
        initialPrice: 220,
        finalPrice: 200,
        validationDuration: { unit: "months", value: 3 },
        redemptionPeriod: { mode: "after_purchase", unit: "day", value: 30 },
        membershipStartDay: "none",
        branchScope: "all",
        branchIds: [],
        createdAt: "2026-02-01T00:00:00Z",
        updatedAt: "2026-02-01T00:00:00Z",
      },
      {
        id: "VCH-003",
        spId: "SP-20260115-0002",
        code: "PACSP000020002",
        name: "Therapy Bundle (5 Sessions)",
        description: "Five individual therapy sessions — valid for 6 months from purchase.",
        serviceLines: [{ serviceCategory: "Psychological Wellbeing", subServiceLabel: "Individual Therapy Bundle", description: "5 sessions package", duration: { unit: "session", value: 5 }, weight: 1.0 }],
        status: "draft",
        isActive: false,
        activationPeriod: { startDate: "2026-04-01T00:00:00Z" },
        currency: "MYR",
        initialPrice: 1000,
        finalPrice: 900,
        validationDuration: { unit: "half_year", value: 1 },
        redemptionPeriod: { mode: "after_purchase", unit: "day", value: 30 },
        membershipStartDay: "none",
        branchScope: "all",
        branchIds: [],
        createdAt: "2026-03-20T00:00:00Z",
        updatedAt: "2026-03-20T00:00:00Z",
      },
    ],
    activeVoucherCount: 1,
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "SP-20260201-0003",
    name: "CoreFit Rehabilitation",
    registrationNo: "9988776-C",
    serviceCategories: ["Medical Rehabilitation", "Holistic Therapy"],
    description: "Sports rehabilitation and physiotherapy specialists.",
    website: "https://corefit.my",
    isActive: true,
    status: "pending",
    taxProfile: { isTaxRegistered: true, taxRegNo: "SST-2024-005678", taxRate: 0.08 },
    commissionSchema: [],
    admins: [
      { id: "SPA-003", spId: "SP-20260201-0003", name: "Chong Wei Lin", email: "wei@corefit.my", status: "pending_activation", invitedAt: "2026-02-03T00:00:00Z" },
    ],
    branches: [],
    vouchers: [],
    activeVoucherCount: 0,
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "SP-20260210-0004",
    name: "Serenity Spa & Aesthetics",
    registrationNo: "3344556-D",
    serviceCategories: ["Personal Care", "Holistic Therapy"],
    description: "Premium spa treatments and aesthetic services.",
    website: "https://serenityspa.my",
    isActive: false,
    status: "suspended",
    taxProfile: { isTaxRegistered: true, taxRegNo: "SST-2023-009012", taxRate: 0.08 },
    commissionSchema: [
      { serviceCategory: "Personal Care", commissionRate: 0.15, expiredCommissionRate: 0.15, lastUpdated: "2026-02-15T00:00:00Z" },
      { serviceCategory: "Holistic Therapy", commissionRate: 0.15, expiredCommissionRate: 0.15, lastUpdated: "2026-02-15T00:00:00Z" },
    ],
    admins: [
      { id: "SPA-004", spId: "SP-20260210-0004", name: "Mei Ling Tan", email: "mei@serenityspa.my", status: "active", invitedAt: "2026-02-12T00:00:00Z" },
    ],
    branches: [
      {
        id: "SPB-004",
        spId: "SP-20260210-0004",
        name: "Serenity Pavilion KL",
        services: ["Personal Care", "Holistic Therapy"],
        address: { line: "Level 5, Pavilion Kuala Lumpur", city: "Kuala Lumpur", state: "Wilayah Persekutuan", country: "Malaysia", postalCode: "55100", lat: 3.1488, lon: 101.7131 },
        contacts: [{ name: "Lena Yap", type: "branch_manager", phone: "+60161234567", isPublic: true }],
        isActive: false,
        operatingHours: DEFAULT_OPERATING_HOURS,
        facilities: ["Private Rooms", "Steam Room", "Relaxation Lounge", "Free WiFi", "Parking"],
      },
    ],
    vouchers: [],
    activeVoucherCount: 0,
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `SP-20260301-000${i + 5}`,
    name: `Wellness Partner ${i + 1} Sdn Bhd`,
    registrationNo: `${7000000 + i}-X`,
    serviceCategories: i % 2 === 0 ? ["Physical Wellbeing"] : ["Nutritional Support", "Preventive Health"],
    description: `Certified wellness centre offering quality health services.`,
    isActive: true,
    status: "active" as const,
    taxProfile: { isTaxRegistered: false, taxRate: 0.08 },
    commissionSchema: [
      { serviceCategory: i % 2 === 0 ? "Physical Wellbeing" : "Nutritional Support", commissionRate: 0.12, expiredCommissionRate: 0.12, lastUpdated: "2026-03-01T00:00:00Z" },
    ],
    admins: [],
    branches: [],
    vouchers: [],
    activeVoucherCount: i + 1,
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  } satisfies ServiceProvider)),
];
