import { Member, Administrator } from "./types";

export const MOCK_MEMBERS: Member[] = [
  {
    id: "mem_1",
    name: "Alex Johnson",
    email: "alex.j@techcorp.com",
    type: "Employee",
    organization: { id: "org_1", name: "TechCorp Solutions" },
    branch: { id: "br_1", name: "Main HQ" },
    status: "Active",
    joinedDate: "15 Jan 2024",
    lastActive: "09 Apr 2024, 17:15",
  },
  {
    id: "mem_2",
    name: "Sarah Johnson",
    email: "sarah.j@gmail.com",
    type: "Dependent",
    organization: { id: "org_1", name: "TechCorp Solutions" },
    status: "Active",
    joinedDate: "10 Feb 2024",
    lastActive: "07 Apr 2024, 10:20",
  },
  {
    id: "mem_3",
    name: "Michael Chen",
    email: "m.chen@welluber.com",
    type: "Employee",
    organization: { id: "org_2", name: "WellUber Global" },
    branch: { id: "br_2", name: "KL Office" },
    status: "Pending",
    joinedDate: "01 Mar 2024",
    lastActive: "01 Mar 2024, 09:00",
  },
];

export const MOCK_ADMINS: Administrator[] = [
  {
    id: "adm_1",
    name: "Yon Yusuf",
    email: "yon@welluber.com",
    role: "HostAdmin",
    status: "Active",
    joinedDate: "01 Jan 2024",
    lastLogin: "06 Apr 2024, 14:30",
    lastActive: "09 Apr 2024, 16:45",
  },
  {
    id: "adm_2",
    name: "Danish Azhar",
    email: "danish@techcorp.com",
    role: "OrgAdmin",
    entity: { id: "org_1", name: "TechCorp Solutions", type: "Organization" },
    status: "Active",
    joinedDate: "15 Jan 2024",
    lastLogin: "05 Apr 2024, 09:15",
    lastActive: "08 Apr 2024, 11:30",
  },
  {
    id: "adm_3",
    name: "Amira Rahman",
    email: "amira@medicare.com",
    role: "SPAdmin",
    entity: { id: "sp_1", name: "MediCare Clinic Group", type: "ServiceProvider" },
    status: "Inactive",
    joinedDate: "10 Feb 2024",
    lastLogin: "20 Mar 2024, 16:45",
    lastActive: "24 Mar 2024, 13:10",
  },
];
