export const MOCK_EMPLOYEE_GRID = [
  {
    id: "EMP-20260115-0001",
    name: "Robert Fox",
    email: "robert.f@acme.com",
    branch: "ACME HQ",
    status: "Linked",
    empCode: "ACM-001",
    joinDate: "12 Oct 2023",
    lastActive: "09 Apr 2026, 17:15",
    department: "Engineering",
    tier: "Manager",
    employmentType: "full-time",
    dependentsCount: 0,
    benefitPolicies: [
      {
        policyName: "Employee Essentials 2026",
        benefitGroups: ["General Wellness"],
        utilisation: 20,
      },
    ],
  },
  {
    id: "EMP-20260115-0002",
    name: "Jenny Wilson",
    email: "jenny.w@acme.com",
    branch: "ACME Subang Jaya",
    status: "Linked",
    empCode: "ACM-042",
    joinDate: "05 Mar 2024",
    lastActive: "09 Apr 2026, 16:45",
    department: "Product",
    tier: "Senior Manager",
    employmentType: "full-time",
    dependentsCount: 2,
    benefitPolicies: [
      {
        policyName: "Acme Family Wellness 2026",
        benefitGroups: ["Physical Wellbeing", "Mental Fitness"],
        utilisation: 15,
      },
    ],
  },
  {
    id: "EMP-20260115-0003",
    name: "Michael Tan",
    email: "michael.t@acme.com",
    branch: "ACME HQ",
    status: "Linked",
    empCode: "ACM-156",
    joinDate: "20 May 2026",
    lastActive: "09 Apr 2026, 10:20",
    department: "Marketing",
    tier: "Associate",
    employmentType: "full-time",
    dependentsCount: 2,
    benefitPolicies: [
      {
        policyName: "Acme Nutrition Plan FY2026",
        benefitGroups: ["Nutrition & Recovery"],
        utilisation: 54,
      },
    ],
  },
  {
    id: "EMP-20260115-0004",
    name: "Marvin McKinney",
    email: "marvin.m@acme.com",
    branch: "ACME HQ",
    status: "Linked",
    empCode: "ACM-089",
    joinDate: "12 Jan 2026",
    lastActive: "08 Apr 2026, 14:30",
    department: "Operations",
    tier: "Manager",
    employmentType: "contract",
    dependentsCount: 0,
    benefitPolicies: [
      {
        policyName: "Contract Staff Essentials 2026",
        benefitGroups: ["Basic Medical"],
        utilisation: 40,
      },
    ],
  },
  {
    id: "EMP-20260115-0006",
    name: "Ahmad Faizal",
    email: "ahmad.f@acme.com",
    branch: "ACME Subang Jaya",
    status: "Linked",
    empCode: "ACM-301",
    joinDate: "15 Jan 2026",
    lastActive: "07 May 2026, 08:45",
    department: "Operations",
    tier: "Senior Manager",
    employmentType: "full-time",
    dependentsCount: 2,
    benefitPolicies: [
      {
        policyName: "Executive Benefits Programme 2026",
        benefitGroups: ["Comprehensive Health", "Wellness Extras"],
        utilisation: 21,
      },
    ],
  },
]

export const MOCK_EMPLOYEE_TABLE = [
  {
    id: "EMP-20260115-0001",
    name: "Robert Fox",
    email: "robert.f@acme.com",
    branch: "ACME HQ",
    joinDate: "12 Oct 2023",
    lastActive: "09 Apr 2026, 17:15",
    status: "Linked",
    empCode: "ACM-001",
    department: "Engineering",
    tier: "Manager",
    employmentType: "full-time",
    benefitPolicies: [
      { policyName: "Employee Essentials 2026", benefitGroups: ["General Wellness"], utilisation: 20 },
    ],
  },
  {
    id: "EMP-20260115-0002",
    name: "Jenny Wilson",
    email: "jenny.w@acme.com",
    branch: "ACME Subang Jaya",
    joinDate: "05 Mar 2026",
    lastActive: "09 Apr 2026, 16:45",
    status: "Linked",
    empCode: "ACM-042",
    department: "Product",
    tier: "Senior Manager",
    employmentType: "full-time",
    benefitPolicies: [
      { policyName: "Acme Family Wellness 2026", benefitGroups: ["Physical Wellbeing", "Mental Fitness"], utilisation: 15 },
    ],
  },
  {
    id: "EMP-20260115-0003",
    name: "Michael Tan",
    email: "michael.t@acme.com",
    branch: "ACME HQ",
    joinDate: "20 May 2026",
    lastActive: "09 Apr 2026, 10:20",
    status: "Linked",
    empCode: "ACM-156",
    department: "Marketing",
    tier: "Associate",
    employmentType: "full-time",
    benefitPolicies: [
      {
        policyName: "Acme Nutrition Plan FY2026",
        benefitGroups: ["Nutrition & Recovery"],
        utilisation: 54,
      },
    ],
  },
  {
    id: "EMP-20260115-0004",
    name: "Marvin McKinney",
    email: "marvin.m@acme.com",
    branch: "ACME HQ",
    joinDate: "12 Jan 2026",
    lastActive: "08 Apr 2026, 14:30",
    status: "Linked",
    empCode: "ACM-089",
    department: "Operations",
    tier: "Manager",
    employmentType: "contract",
    benefitPolicies: [
      { policyName: "Contract Staff Essentials 2026", benefitGroups: ["Basic Medical"], utilisation: 40 },
    ],
  },
  {
    id: "EMP-20260115-0006",
    name: "Ahmad Faizal",
    email: "ahmad.f@acme.com",
    branch: "ACME Subang Jaya",
    joinDate: "15 Jan 2026",
    lastActive: "07 May 2026, 08:45",
    status: "Linked",
    empCode: "ACM-301",
    department: "Operations",
    tier: "Senior Manager",
    employmentType: "full-time",
    benefitPolicies: [
      {
        policyName: "Executive Benefits Programme 2026",
        benefitGroups: ["Comprehensive Health", "Wellness Extras"],
        utilisation: 21,
      },
    ],
  },
]
