export const MOCK_EMPLOYEE_GRID = [
  {
    id: "EMP-20260115-0001",
    name: "Robert Fox",
    email: "robert.f@acme.com",
    branch: "ACME HQ",
    status: "Linked",
    empCode: "ACM-001",
    joinDate: "12 Oct 2023",
    lastActive: "09 Apr 2026, 17:15",
    department: "Engineering",
    tier: "Manager",
    employmentType: "full-time",
    dependentsCount: 2,
    benefitPolicies: [
      {
        policyName: "Acme Employee Wellness Policy FY2026",
        benefitGroups: ["Gym Membership", "Mental Health"],
        utilisation: 48,
      },
      {
        policyName: "Corporate Perks",
        benefitGroups: ["Book Allowance", "Home Office"],
        utilisation: 10,
      },
    ],
  },
  {
    id: "EMP-20260115-0002",
    name: "Jenny Wilson",
    email: "jenny.w@acme.com",
    branch: "ACME Subang Jaya",
    status: "Linked",
    empCode: "ACM-042",
    joinDate: "05 Mar 2024",
    lastActive: "09 Apr 2026, 16:45",
    department: "Product",
    tier: "Senior Manager",
    employmentType: "full-time",
    dependentsCount: 0,
    benefitPolicies: [
      {
        policyName: "Acme Leadership Benefits Policy FY2026",
        benefitGroups: ["Travel", "Food"],
        utilisation: 85,
      },
    ],
  },
  {
    id: "EMP-20260115-0003",
    name: "Dianne Russell",
    email: "dianne.r@globalhealth.com",
    branch: "ACME HQ",
    status: "Pending Invite",
    empCode: "ACM-156",
    joinDate: "20 May 2026",
    lastActive: "09 Apr 2026, 10:20",
    department: "Growth",
    tier: "Associate",
    employmentType: "internship",
    dependentsCount: 1,
    benefitPolicies: [
      {
        policyName: "Rejuvenation Fund",
        benefitGroups: ["Spa Sessions", "Massages", "Facials", "Manicures", "Pedicures", "Aromatherapy", "Hot Stone"],
        utilisation: 15,
      },
    ],
  },
]

export const MOCK_EMPLOYEE_TABLE = [
  {
    id: "EMP-20260115-0001",
    name: "Robert Fox",
    email: "robert.f@acme.com",
    branch: "ACME HQ",
    joinDate: "12 Oct 2023",
    lastActive: "09 Apr 2026, 17:15",
    status: "Linked",
    empCode: "ACM-001",
    department: "Engineering",
    tier: "Manager",
    employmentType: "full-time",
    benefitPolicies: [
      { policyName: "Acme Employee Wellness Policy FY2026", benefitGroups: ["Gym", "Mental Health"], utilisation: 48 },
      { policyName: "Corporate Perks" },
    ],
  },
  {
    id: "EMP-20260115-0002",
    name: "Jenny Wilson",
    email: "jenny.w@acme.com",
    branch: "ACME Subang Jaya",
    joinDate: "05 Mar 2026",
    lastActive: "09 Apr 2026, 16:45",
    status: "Linked",
    empCode: "ACM-042",
    department: "Product",
    tier: "Senior Manager",
    employmentType: "full-time",
    benefitPolicies: [
      { policyName: "Acme Leadership Benefits Policy FY2026", benefitGroups: ["Food", "Travel"], utilisation: 85 },
    ],
  },
  {
    id: "EMP-20260115-0003",
    name: "Dianne Russell",
    email: "dianne.r@globalhealth.com",
    branch: "Global Health HQ",
    joinDate: "20 May 2026",
    lastActive: "09 Apr 2026, 10:20",
    status: "Pending",
    empCode: "ACM-156",
    department: "Growth",
    tier: "Associate",
    employmentType: "internship",
    benefitPolicies: [
      {
        policyName: "Rejuvenation Fund",
        benefitGroups: ["Spa Sessions", "Massages", "Facials", "Manicures", "Pedicures", "Aromatherapy", "Hot Stone"],
        utilisation: 15,
      },
    ],
  },
  {
    id: "EMP-20260115-0004",
    name: "Marvin McKinney",
    email: "marvin.m@zenithwellness.com",
    branch: "Zenith HQ",
    joinDate: "12 Jan 2026",
    lastActive: "08 Apr 2026, 14:30",
    status: "Linked",
    empCode: "ACM-089",
    department: "Sales",
    tier: "Manager",
    employmentType: "contract",
    benefitPolicies: [
      { policyName: "Mental Health Support", benefitGroups: ["Counseling", "Meditation Apps"], utilisation: 12 },
      { policyName: "Development Fund" },
      { policyName: "WFH Allowance" },
      { policyName: "Wellness Extras" },
    ],
  },
]
