export const MOCK_BRANCHES = [
  {
    id: "br_1",
    name: "ACME HQ (Kuala Lumpur)",
    type: "HQ",
    status: "Active",
    employees: 1240,
    accountModel: "New",
    accountName: "KL HQ Account",
    accountId: "ACC-20260115-0001",
    cashBalance: 45000,
    creditBalance: 10000,
    claimsCount: 12,
    address: { city: "Kuala Lumpur", state: "Wilayah Persekutuan" },
    employeesCount: 1240,
  },
  {
    id: "br_2",
    name: "ACME Subang Jaya",
    type: "Branch office",
    status: "Active",
    employees: 450,
    accountModel: "Existing",
    accountName: "Subang Shared Pool",
    accountId: "ACC-20260115-0002",
    cashBalance: 12500,
    creditBalance: 5000,
    claimsCount: 5,
    address: { city: "Subang Jaya", state: "Selangor" },
    employeesCount: 450,
  },
]
